kind: Service
apiVersion: v1
metadata:
  name: java-example-service
spec:
  selector:
    app: php-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-example
  labels:
    app: java-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-example
  template:
    metadata:
      labels:
        app: java-example
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: java
        image: giaple/demogo:latest
        ports:
        - containerPort: 8080
--------------
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: giaplv-java-app          
---
