apiVersion: v1
kind: Service
metadata:
  name: java-example-service
spec:
  selector:
    app: java-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # tên của deployment
  name: java-example
spec:
  # số POD tạo ra
  replicas: 1
  # thiết lập các POD do deploy quản lý, là POD có nhãn  "app=deployapp"
  selector:
    matchLabels:
      app: java-example

  # Định nghĩa mẫu POD, khi cần Deploy sử dụng mẫu này để tạo Pod
  template:
    metadata:
      name: podapp-java
      labels:
        app: java-example
    spec:
      containers:
      - name: node
        #image: ichte/swarmtest:node
        image: giaple/demogo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 8080
---
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: giaplv-app-java 